#! /bin/sh

sh ~/.config/bspwm/autostart.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "#8C64E4"  # Background
bspc config active_border_color "#268BD2"  # Selected background
bspc config focused_border_color "#63C77E" # Blue
bspc config urgent_border_color "#EF6155"  # Urgentbspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
